/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import java.util.ArrayList;
import points.Point;
import points.PointFactory;
import traverse.Traverse;

/**
 *
 * @author John
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    ArrayList<Point> points;
    PointFactory pointFactory;
    ArrayList<Traverse> traverses;
    
    public MainFrame(ArrayList thesePoints, PointFactory thisPointFactory, ArrayList theseTraverses) {
        initComponents();
        this.points = thesePoints;
        this.pointFactory = thisPointFactory;
        this.traverses = theseTraverses;
        
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainMenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        QuitMenuItem = new javax.swing.JMenuItem();
        PointMenu = new javax.swing.JMenu();
        CreatePointMenu = new javax.swing.JMenu();
        ByCooridinateItem = new javax.swing.JMenuItem();
        CreatePointByAzimuthMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        EditPointMenu = new javax.swing.JMenu();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        ListPointsMenuItem = new javax.swing.JMenuItem();
        TraverseMenu = new javax.swing.JMenu();
        NewTraverseMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FileMenu.setText("File");

        QuitMenuItem.setText("Quit");
        QuitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitMenuItemActionPerformed(evt);
            }
        });
        FileMenu.add(QuitMenuItem);

        MainMenuBar.add(FileMenu);

        PointMenu.setText("Points");
        PointMenu.setToolTipText("");

        CreatePointMenu.setText("CreatePoint");

        ByCooridinateItem.setText("By Coordinate");
        ByCooridinateItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ByCooridinateItemActionPerformed(evt);
            }
        });
        CreatePointMenu.add(ByCooridinateItem);

        CreatePointByAzimuthMenuItem.setText("By Azimuth");
        CreatePointByAzimuthMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreatePointByAzimuthMenuItemActionPerformed(evt);
            }
        });
        CreatePointMenu.add(CreatePointByAzimuthMenuItem);

        PointMenu.add(CreatePointMenu);
        PointMenu.add(jSeparator1);

        EditPointMenu.setText("Edit Point");
        PointMenu.add(EditPointMenu);
        PointMenu.add(jSeparator2);

        ListPointsMenuItem.setText("List Points");
        ListPointsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListPointsMenuItemActionPerformed(evt);
            }
        });
        PointMenu.add(ListPointsMenuItem);

        MainMenuBar.add(PointMenu);

        TraverseMenu.setText("Traverse");

        NewTraverseMenuItem.setText("New Traverse");
        NewTraverseMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewTraverseMenuItemActionPerformed(evt);
            }
        });
        TraverseMenu.add(NewTraverseMenuItem);

        MainMenuBar.add(TraverseMenu);

        setJMenuBar(MainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ByCooridinateItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ByCooridinateItemActionPerformed
        Point newPoint = pointFactory.createPointByCoordinate(points);
        PointByCoordinateDialog dialog = new PointByCoordinateDialog(this, points, newPoint, true);
        points.add(newPoint);
    }//GEN-LAST:event_ByCooridinateItemActionPerformed

    private void QuitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitMenuItemActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_QuitMenuItemActionPerformed

    private void ListPointsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListPointsMenuItemActionPerformed
        String report = "     Label             Norhing             Easting           Elevation                   Description\n";
        for(int i = 0; i < points.size(); i++){
            report += points.get(i).printPoint();
        }
        
        ViewReport pointList = new ViewReport(report);
    }//GEN-LAST:event_ListPointsMenuItemActionPerformed

    private void NewTraverseMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewTraverseMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewTraverseMenuItemActionPerformed

    private void CreatePointByAzimuthMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreatePointByAzimuthMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreatePointByAzimuthMenuItemActionPerformed

    public javax.swing.JMenu getEditPointMenu(){
        return EditPointMenu;
    }
    
    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */ /*
         try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form *//*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ByCooridinateItem;
    private javax.swing.JMenuItem CreatePointByAzimuthMenuItem;
    private javax.swing.JMenu CreatePointMenu;
    private javax.swing.JMenu EditPointMenu;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenuItem ListPointsMenuItem;
    private javax.swing.JMenuBar MainMenuBar;
    private javax.swing.JMenuItem NewTraverseMenuItem;
    private javax.swing.JMenu PointMenu;
    private javax.swing.JMenuItem QuitMenuItem;
    private javax.swing.JMenu TraverseMenu;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
